attributes:
  domain_name:
    value: 'example.com'
    label: 'LDAP Domain name'
    description: 'Domain name'
    weight: 5
    type: text
    regex:
      source: '^[a-zA-Z0-9._-]+$'
      error: 'Domain name contains invalid characters'
  uri:
    value: 
      - 'ldaps://example.com'
    label: 'LDAP URI'
    description: 'LDAP URI'
    weight: 10
    type: text_list
    min: 1
    max: 64
    regex:
      source: '^ldap[s]?:\/\/([a-zA-Z0-9._-]+)(:[0-9]+)?$'
      error: 'Not a valid LDAP URI. Should be e.g. ldap://example.com'
  binduser:
    value: 'cn=ldapreader,ou=ServiceAccounts,dc=example,dc=com'
    label: 'LDAP User'
    description: 'Account to query LDAP server'
    weight: 15
    type: text
    regex:
      source: '^[a-zA-Z0-9_,=\S\\]+$'
      error: "Account name contains invalid character or is empty"
  bindpass:
    value: 'password'
    label: 'LDAP Password'
    description: 'Password to query LDAP server'
    weight: 20
    type: password
    regex:
      source: '^\S+$'
      error: "Password can't be empty or contain spaces"
  passw_auth:
    value: false
    label: "Allow authentication by password"
    description: "It set 'PasswordAuthentication' param of 'ssh' service to 'yes'."
    weight: 25
    type: "checkbox"
  use_tls:
    value: false
    label: 'Use TLS'
    description: 'Use TLS when communicating with LDAP server'
    weight: 30
    type: checkbox
  tls_cacert:
    value: ''
    label: 'CA Cerificate'
    description: 'CA Certificate that signed LDAP server certificate'
    weight: 35
    type: textarea
    restrictions:
      - condition: 'settings:ldap-slaves.use_tls.value == false'
        action: 'disable'
    regex:
      source: '^(-----BEGIN CERTIFICATE-----)(.*[\r\n])+(-----END CERTIFICATE-----[\s\S]*?)$|^$'
      error: 'The certificate is not in valid PEM format'
  search_base:
    value: 'dc=example,dc=com'
    label: 'Search base'
    description: 'Search base defines the location in the LDAP directory where to start looking for objects'
    weight: 40
    type: text
  access_filter:
    value: ''
    label: 'LDAP Access filter'
    description: 'Access filter allows to limit access to Openstack Servers to specified group'
    weight: 45
    type: text
  home_directory_attr:
    value: 'homeDirectory'
    label: 'Home Directory Attribute'
    description: 'Attribute name in user object, that holds path to user home directory, that should be created during first login'
    weight: 50
    type: text
  ssh_key_attr:
    value: 'sshPublicKey'
    label: 'SSH Public Key Attribute'
    description: 'Attribute name in user object, that holds users public key'
    weight: 55
    type: text
